server:
  port: 9001
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: auth  #路由的id,建议与服务名一致
          uri: lb://auth  #匹配后提供服务的路由地址
          predicates:
            - Path=/auth/** #断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1 #去除security进行路由匹配
        - id: resource  #路由的id,建议与服务名一致
          uri: lb://resource  #匹配后提供服务的路由地址
          predicates:
            - Path=/resource/** #断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1 #去除user进行路由匹配
        - id: test  #路由的id,建议与服务名一致
          uri: lb://test  #匹配后提供服务的路由地址
          predicates:
            - Path=/test/** #断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1 #去除user进行路由匹配